# cross_val_score

## About

Method to test models power

## jpegn't example (rus)

![gif](jpgn't.gif)

## jpegn't example (eng)

But very small

![png](down.png)

## Imports

In [159]:
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score

import numpy as np
import pandas as pd

import random

## Load Data and Model

In [168]:
iris = load_iris()
logreg = LogisticRegression()

## Help-function

In [173]:
def pr_res(model, X, Y, cv=3):
    
    cross_vs = cross_val_score(model, X, Y, cv=cv)

    print('SCORES:\n{}\n\n'.format(cross_vs))
    print('MEAN:\n{}'.format(cross_vs.mean()))

## cv:3

In [174]:
pr_res(logreg, iris.data, iris.target, cv=3)

SCORES:
[0.96078431 0.92156863 0.95833333]


MEAN:
0.9468954248366014


## cv: 5

In [175]:
pr_res(logreg, iris.data, iris.target, cv=5)

SCORES:
[1.         0.96666667 0.93333333 0.9        1.        ]


MEAN:
0.9600000000000002


## cv: 8

In [180]:
pr_res(logreg, iris.data, iris.target, cv=8)

SCORES:
[1.         1.         0.94444444 0.94444444 0.94444444 0.83333333
 1.         1.        ]


MEAN:
0.9583333333333333


### One thing

There is non-shuffle-data

And this result was the same

## Shuffling

In [176]:
all_iris = pd.DataFrame(iris.data, columns=iris.feature_names)
all_iris['target'] = iris.target

values = all_iris.values
np.random.shuffle(values)

all_iris_sh = pd.DataFrame(values)
X = all_iris_sh.iloc[:,:-1]
Y = all_iris_sh[4]

## cv: 3

In [178]:
pr_res(logreg, X, Y, cv=3)

SCORES:
[0.96078431 0.94117647 0.89583333]


MEAN:
0.9325980392156863


## cv: 5

In [179]:
pr_res(logreg, X, Y, cv=5)

SCORES:
[1.         0.96666667 0.96666667 0.93333333 0.93333333]


MEAN:
0.9600000000000002


## cv: 8

In [181]:
pr_res(logreg, X, Y, cv=8)

SCORES:
[1.         1.         0.94444444 0.94444444 1.         0.88888889
 0.94444444 0.94444444]


MEAN:
0.9583333333333333


## Agressive total

- SHUFLE YOUR DATA!
- MAKE YOUR DATA BIG!
- TEST YOUR MODEL BEFORE!
- TRY HARD!

![gif](tenor.gif)