# NumPy

![gif](imgs/N002.gif)

## Import

In [1]:
import numpy as np

## Making array

### array

In [2]:
data = [0.9526, -0.246 , -0.835, 0.5639, 0.2379, 0.9104]
arr = np.array(data)
arr

array([ 0.9526, -0.246 , -0.835 ,  0.5639,  0.2379,  0.9104])

In [3]:
type(arr)

numpy.ndarray

In [4]:
arr * 10

array([ 9.526, -2.46 , -8.35 ,  5.639,  2.379,  9.104])

In [5]:
arr + arr

array([ 1.9052, -0.492 , -1.67  ,  1.1278,  0.4758,  1.8208])

In [6]:
arr.shape

(6,)

In [7]:
arr.dtype

dtype('float64')

### asarray

In [8]:
data = [6, 7.5, 8, 0, 1]
arr = np.asarray(data)
arr

array([6. , 7.5, 8. , 0. , 1. ])

In [9]:
type(arr)

numpy.ndarray

In [10]:
data = [[6, 7.5, 8, 0, 1], [0.9526, -0.246 , -0.835, 0.5639, 0.1241]]
arr = np.array(data)
arr

array([[ 6.    ,  7.5   ,  8.    ,  0.    ,  1.    ],
       [ 0.9526, -0.246 , -0.835 ,  0.5639,  0.1241]])

In [11]:
arr.ndim

2

In [12]:
arr.shape

(2, 5)

In [13]:
arr.dtype

dtype('float64')

### zeros

In [14]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
np.zeros(100)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [17]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

### ones

In [18]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [19]:
np.ones((5,4,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

### empty

In [20]:
np.empty(5)

array([6. , 7.5, 8. , 0. , 1. ])

In [21]:
np.empty(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
np.empty((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [23]:
np.empty((4,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

### arange

In [24]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [25]:
np.arange(-1)

array([], dtype=int32)

### eye

In [26]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [27]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Type of data

### main

In [28]:
arr1 = np.array([1,2,3], dtype=np.float64)
arr2 = np.array([1,2,3], dtype=np.int32)

In [29]:
arr1.dtype

dtype('float64')

In [30]:
arr2.dtype

dtype('int32')

### other

In [31]:
# np.bool   — BOOL
# np.object — STR/OBJ

### astype

#### int → floaf

In [32]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [33]:
arr.dtype

dtype('int32')

In [34]:
float_arr = arr.astype(np.float64)
float_arr

array([1., 2., 3., 4., 5.])

In [35]:
float_arr.dtype

dtype('float64')

#### float → int

In [36]:
arr = np.array([1.123, 5.734, 3.937, 9.627])
arr

array([1.123, 5.734, 3.937, 9.627])

In [37]:
arr.dtype

dtype('float64')

In [38]:
arr = arr.astype(np.int32)
arr

array([1, 5, 3, 9])

In [39]:
arr.dtype

dtype('int32')

#### str → float

In [40]:
str_num = ['1.412', '9.125', '7.522']
arr_str_num = np.array(str_num, dtype=np.string_)
arr_str_num

array([b'1.412', b'9.125', b'7.522'], dtype='|S5')

In [41]:
arr_str_num = arr_str_num.astype(np.float64)
arr_str_num

array([1.412, 9.125, 7.522])

In [42]:
arr_str_num.dtype

dtype('float64')

#### foreign dtype

In [43]:
int_arr = np.arange(10)
int_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
int_arr.dtype

dtype('int32')

In [45]:
flt_arr = np.array(['1', '24', '4', '214', '2', '1'], dtype=np.object)
flt_arr

array(['1', '24', '4', '214', '2', '1'], dtype=object)

In [46]:
flt_arr = flt_arr.astype(int_arr.dtype)
flt_arr

array([  1,  24,   4, 214,   2,   1])

In [47]:
flt_arr.dtype == int_arr.dtype

True

## Matrix & scalars

In [48]:
arr = np.array([[1., 2., 3.],[4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [49]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [50]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [51]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [52]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

## Indexing

In [53]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
arr[5]

5

In [55]:
arr[5:8]

array([5, 6, 7])

In [56]:
arr[5:8] = 999
arr

array([  0,   1,   2,   3,   4, 999, 999, 999,   8,   9])

### warning

In [57]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
arr_slice = arr[5:8]
arr_slice[1] = 666
arr

array([  0,   1,   2,   3,   4,   5, 666,   7,   8,   9])

In [59]:
arr_slice[:] = 777
arr

array([  0,   1,   2,   3,   4, 777, 777, 777,   8,   9])

### resolving

In [60]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
arr_slice = arr[5:8].copy()
arr_slice[:] = 108
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
arr_slice

array([108, 108, 108])

### 2D array

In [63]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [64]:
arr2d[2]

array([7, 8, 9])

In [65]:
arr2d[0][2]

3

In [66]:
arr2d[0, 2]

3

### 3D array

In [67]:
arr3d = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [68]:
arr3d.shape

(2, 2, 3)

In [69]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [70]:
bu_values = arr3d[0].copy()

arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [71]:
bu_values

array([[1, 2, 3],
       [4, 5, 6]])

In [72]:
arr3d[0] = bu_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [73]:
arr3d[1, 0]

array([7, 8, 9])

In [74]:
arr3d[1, 1, 1]

11

## Slicing

In [75]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [76]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [77]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])