# Numpy

![gif](imgs/N003.gif)

## Import

In [57]:
import numpy as np
from random import normalvariate

## File-In-Out array

In [58]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### save

In [59]:
np.save('files/some_array', arr)

### load

In [60]:
np.load('files/some_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### save zip

In [61]:
np.savez('files/array_zip.npz', a=arr, b=arr)

In [62]:
ziparray = np.load('files/array_zip.npz')

ziparray['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
ziparray['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Linear math

### dot

In [64]:
x = np.array([[1,2], [3,4], [5,6]])
y = np.array([[1,2, 3], [4, 5, 6]])

x

array([[1, 2],
       [3, 4],
       [5, 6]])

In [65]:
y

array([[1, 2, 3],
       [4, 5, 6]])

In [66]:
x.shape

(3, 2)

In [67]:
y.shape

(2, 3)

In [68]:
x.dot(y)

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

In [69]:
y.dot(x)

array([[22, 28],
       [49, 64]])

In [70]:
np.dot(x, y)

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

In [71]:
np.dot(y, x)

array([[22, 28],
       [49, 64]])

### numpy.linalg

In [72]:
X = np.random.randn(5,5)
X

array([[-0.70280395, -1.21398416,  1.17601956, -1.07202697, -0.29216844],
       [ 0.85967793,  0.01476934, -0.09857485,  0.13400173, -2.59249598],
       [-1.26148687,  0.78935598,  1.22349472, -0.43841611, -0.88759236],
       [ 0.39271283, -0.4016056 , -1.41429729,  1.06717745,  0.17711229],
       [ 0.02096482,  0.36592712, -0.88015025,  0.89928711,  0.20679675]])

In [73]:
mat = X.T.dot(X)
mat

array([[ 2.97899156, -0.27991654, -3.02854123,  1.85962697, -0.82979862],
       [-0.27991654,  2.39224824, -0.21743326,  0.85782559, -0.37968468],
       [-3.02854123, -0.21743326,  5.66457963, -4.11114765, -1.60650711],
       [ 1.85962697,  0.85782559, -4.11114765,  3.306992  ,  0.72992818],
       [-0.82979862, -0.37968468, -1.60650711,  0.72992818,  7.66835167]])

In [74]:
np.linalg.inv(mat)

array([[  95.33219787,  -57.36684038,  255.81657769,  271.52093808,
          35.22342158],
       [ -57.36684038,   35.72589748, -155.90244673, -166.12237421,
         -21.28740877],
       [ 255.81657769, -155.90244673,  691.7082787 ,  735.55919746,
          94.85889386],
       [ 271.52093808, -166.12237421,  735.55919746,  782.8991169 ,
         100.73280006],
       [  35.22342158,  -21.28740877,   94.85889386,  100.73280006,
          13.17227305]])

In [75]:
res = mat.dot(np.linalg.inv(mat))
res.astype(np.float16).astype(np.float64)

array([[ 1., -0., -0., -0., -0.],
       [-0.,  1., -0., -0., -0.],
       [-0.,  0.,  1.,  0., -0.],
       [ 0., -0.,  0.,  1.,  0.],
       [ 0.,  0.,  0., -0.,  1.]])

In [76]:
q, r = np.linalg.qr(mat)
q

array([[-0.63123885,  0.1634649 , -0.32575967,  0.64004103,  0.24299147],
       [ 0.05931343, -0.93093968, -0.05384516,  0.32460466, -0.14685282],
       [ 0.64173826,  0.02808361, -0.34385045,  0.2022922 ,  0.65439135],
       [-0.39404905, -0.29754125,  0.31922747, -0.41398596,  0.69491295],
       [ 0.17583169,  0.13157151,  0.81904946,  0.5221808 ,  0.09086994]])

In [77]:
r

array([[-4.71927793e+00, -2.25734567e-01,  6.87153261e+00,
        -4.93604151e+00,  5.31035388e-01],
       [ 0.00000000e+00, -2.58409583e+00,  8.78304360e-01,
        -1.49798480e+00,  9.64456941e-01],
       [ 0.00000000e+00,  0.00000000e+00, -3.57768398e+00,
         2.41516871e+00,  7.35692976e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        -3.50855128e-01,  2.72274953e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  6.89857669e-03]])

## Random number generation

### normal

In [78]:
samp = np.random.normal(size=(4,4))
samp

array([[-0.75814029,  1.12473371,  0.07321268, -0.49406462],
       [-1.68349606,  0.41777538,  0.85810033,  2.36977306],
       [ 1.93699997,  0.81294668, -0.56916545,  0.86622721],
       [-1.35649159, -0.94824277,  0.70571237,  2.31421474]])

### comparsion numpy & python-inner-module

In [79]:
N = 1000000

%timeit samp = [normalvariate(0,1) for _ in range(N)]

%timeit samp = np.random.normal(size=N)

799 ms ± 22.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
31.1 ms ± 1.05 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


### same parts of random module

In [80]:
np.random.seed(seed=0)
np.random.randint(0, 100)

44

In [81]:
np.random.seed(seed=0)
np.random.randint(0, 100)

44

In [82]:
np.random.seed(seed=None)

In [83]:
np.random.binomial(5, 0.5, size=(10,10))

array([[0, 3, 2, 3, 1, 1, 3, 3, 1, 3],
       [1, 0, 1, 3, 3, 4, 2, 1, 4, 2],
       [2, 2, 2, 3, 1, 1, 1, 4, 2, 3],
       [1, 2, 2, 2, 4, 3, 4, 2, 4, 2],
       [1, 3, 4, 3, 4, 3, 3, 2, 3, 2],
       [3, 3, 4, 2, 4, 1, 4, 2, 1, 1],
       [1, 2, 2, 5, 1, 1, 4, 1, 1, 3],
       [1, 1, 3, 2, 1, 3, 2, 2, 1, 1],
       [3, 3, 2, 3, 2, 2, 2, 3, 3, 1],
       [2, 3, 2, 4, 1, 2, 3, 2, 2, 1]])

In [84]:
np.random.chisquare(2, size=(5,5))

array([[2.53208475, 0.55913012, 1.55163244, 1.92929581, 3.08651928],
       [1.95037798, 1.31148147, 1.75056827, 0.70609974, 0.69911837],
       [0.80043595, 3.36379307, 2.11395116, 1.04014233, 7.30676566],
       [4.79410801, 2.16993579, 0.01898945, 3.85677145, 2.50354293],
       [4.00941032, 0.99162669, 1.91065537, 1.36737239, 7.30276366]])