# Data Formating

![gif](imgs/DF001.gif)

## Import

In [1]:
import pandas as pd
import numpy as np

## Merge

### equal keys

In [2]:
df1 = pd.DataFrame({'key': ['a', 'b', 'z', 'x', 'c', 's'], 'data1': range(6)})
df1

key  data1
0   a      0
1   b      1
2   z      2
3   x      3
4   c      4
5   s      5

In [3]:
df2 = pd.DataFrame({'key': ['a', 'x', 'c'], 'data2': range(3)})
df2

key  data2
0   a      0
1   x      1
2   c      2

In [4]:
pd.merge(df1, df2)

key  data1  data2
0   a      0      0
1   x      3      1
2   c      4      2

In [5]:
pd.merge(df2, df1)

key  data2  data1
0   a      0      0
1   x      1      3
2   c      2      4

In [6]:
pd.merge(df1, df2, on='key')

key  data1  data2
0   a      0      0
1   x      3      1
2   c      4      2

### how

In [7]:
pd.merge(df1, df2, on='key', how='left')

key  data1  data2
0   a      0    0.0
1   b      1    NaN
2   z      2    NaN
3   x      3    1.0
4   c      4    2.0
5   s      5    NaN

In [8]:
pd.merge(df1, df2, on='key', how='right')

key  data1  data2
0   a      0      0
1   x      3      1
2   c      4      2

In [9]:
pd.merge(df1, df2, on='key', how='outer')

key  data1  data2
0   a      0    0.0
1   b      1    NaN
2   z      2    NaN
3   x      3    1.0
4   c      4    2.0
5   s      5    NaN

### different keys

In [10]:
df1 = pd.DataFrame({'lkey': ['a', 'b', 'z', 'x', 'c', 's'], 'data1': range(6)})
df1

lkey  data1
0    a      0
1    b      1
2    z      2
3    x      3
4    c      4
5    s      5

In [11]:
df2 = pd.DataFrame({'rkey': ['a', 'x', 'c'], 'data2': range(3)})
df2

rkey  data2
0    a      0
1    x      1
2    c      2

In [12]:
pd.merge(df1, df2, left_on='lkey', right_on='rkey')

lkey  data1 rkey  data2
0    a      0    a      0
1    x      3    x      1
2    c      4    c      2

## Same keys

In [13]:
df1 = pd.DataFrame({'key1': ['foo', 'foo', 'bar'], 'key2': ['one', 'two', 'one'], 'lval': [1,2,3]})
df1

key1 key2  lval
0  foo  one     1
1  foo  two     2
2  bar  one     3

In [14]:
df2 = pd.DataFrame({'key1': ['foo', 'foo', 'bar', 'bar'], 'key2': ['one', 'one', 'one', 'two'], 'lval': [4,5,6,7]})
df2

key1 key2  lval
0  foo  one     4
1  foo  one     5
2  bar  one     6
3  bar  two     7

In [15]:
pd.merge(df1, df2, on=['key1', 'key2'], how='inner')

key1 key2  lval_x  lval_y
0  foo  one       1       4
1  foo  one       1       5
2  bar  one       3       6

In [16]:
pd.merge(df1, df2, on=['key1', 'key2'], how='left')

key1 key2  lval_x  lval_y
0  foo  one       1     4.0
1  foo  one       1     5.0
2  foo  two       2     NaN
3  bar  one       3     6.0

In [17]:
pd.merge(df1, df2, on=['key1', 'key2'], how='right')

key1 key2  lval_x  lval_y
0  foo  one     1.0       4
1  foo  one     1.0       5
2  bar  one     3.0       6
3  bar  two     NaN       7

In [18]:
pd.merge(df1, df2, on=['key1', 'key2'], how='outer')

key1 key2  lval_x  lval_y
0  foo  one     1.0     4.0
1  foo  one     1.0     5.0
2  foo  two     2.0     NaN
3  bar  one     3.0     6.0
4  bar  two     NaN     7.0

In [19]:
pd.merge(df1, df2, on=['key1', 'key2'], how='outer', suffixes=('_left', '_right'))

key1 key2  lval_left  lval_right
0  foo  one        1.0         4.0
1  foo  one        1.0         5.0
2  foo  two        2.0         NaN
3  bar  one        3.0         6.0
4  bar  two        NaN         7.0

## Index merge

In [20]:
df1 = pd.DataFrame({'key': ['a', 'b', 'a', 'a', 'b', 'c'], 'data': range(6)})
df1

key  data
0   a     0
1   b     1
2   a     2
3   a     3
4   b     4
5   c     5

In [21]:
df2 = pd.DataFrame({'group': [3.5, 7]}, index=['a', 'b'])
df2

group
a    3.5
b    7.0

In [22]:
pd.merge(df1, df2, left_on='key', right_index=True)

key  data  group
0   a     0    3.5
2   a     2    3.5
3   a     3    3.5
1   b     1    7.0
4   b     4    7.0

In [23]:
pd.merge(df1, df2, left_on='key', right_index=True, how='outer')

key  data  group
0   a     0    3.5
2   a     2    3.5
3   a     3    3.5
1   b     1    7.0
4   b     4    7.0
5   c     5    NaN

### more hard situation

In [24]:
df1 = pd.DataFrame({'key1': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'], 
                    'key2': [2000, 2001, 2002, 2001, 2002],
                    'data': np.arange(5.)}) 
df1

key1  key2  data
0    Ohio  2000   0.0
1    Ohio  2001   1.0
2    Ohio  2002   2.0
3  Nevada  2001   3.0
4  Nevada  2002   4.0

In [25]:
df2 = pd.DataFrame(np.arange(12).reshape((6, 2)), 
                   index=[['Nevada', 'Nevada', 'Ohio', 'Ohio', 'Ohio', 'Ohio'],
                          [2001, 2000, 2000, 2000, 2001, 2002]],
                   columns=['event1', 'event2'])
df2

event1  event2
Nevada 2001       0       1
       2000       2       3
Ohio   2000       4       5
       2000       6       7
       2001       8       9
       2002      10      11

In [26]:
pd.merge(df1, df2, left_on=['key1', 'key2'], right_index=True)

key1  key2  data  event1  event2
0    Ohio  2000   0.0       4       5
0    Ohio  2000   0.0       6       7
1    Ohio  2001   1.0       8       9
2    Ohio  2002   2.0      10      11
3  Nevada  2001   3.0       0       1

## Join

In [27]:
df1 = pd.DataFrame([1,2,3,4,5,6], index=list('abcdef'), columns=['A'])
df1

A
a  1
b  2
c  3
d  4
e  5
f  6

In [28]:
df2 = pd.DataFrame([9,4,4,3], index=list('acef'), columns=['B'])
df2

B
a  9
c  4
e  4
f  3

In [29]:
df1.join(df2)

A    B
a  1  9.0
b  2  NaN
c  3  4.0
d  4  NaN
e  5  4.0
f  6  3.0

In [30]:
df1.join(df2, how='outer')

A    B
a  1  9.0
b  2  NaN
c  3  4.0
d  4  NaN
e  5  4.0
f  6  3.0

## Concat

### numpy

In [31]:
arr = np.arange(12).reshape((3,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [32]:
np.concatenate([arr, arr])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [33]:
np.concatenate([arr, arr], axis=1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

### pandas

### series

In [34]:
s1 = pd.Series([0,1], index=['a', 'b'])
s1

a    0
b    1
dtype: int64

In [35]:
s2 = pd.Series([2,3,4], index=['c', 'd', 'e'])
s2

c    2
d    3
e    4
dtype: int64

In [36]:
s3 = pd.Series([5,6], index=['f', 'g'])
s3

f    5
g    6
dtype: int64

In [37]:
pd.concat([s1,s2,s3])

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int64

In [38]:
pd.concat([s1,s2,s3], axis=1, sort=True)

0    1    2
a  0.0  NaN  NaN
b  1.0  NaN  NaN
c  NaN  2.0  NaN
d  NaN  3.0  NaN
e  NaN  4.0  NaN
f  NaN  NaN  5.0
g  NaN  NaN  6.0

In [39]:
pd.concat([s1,s2,s3], axis=1, join_axes=[['a', 'c', 'b', 'e']])

0    1   2
a  0.0  NaN NaN
c  NaN  2.0 NaN
b  1.0  NaN NaN
e  NaN  4.0 NaN

In [40]:
pd.concat([s1,s2,s3], keys=['one', 'two', 'three'])

one    a    0
       b    1
two    c    2
       d    3
       e    4
three  f    5
       g    6
dtype: int64

In [41]:
r = pd.concat([s1,s2,s3], axis=1, sort=True, keys=['one', 'two', 'three'])
r

one  two  three
a  0.0  NaN    NaN
b  1.0  NaN    NaN
c  NaN  2.0    NaN
d  NaN  3.0    NaN
e  NaN  4.0    NaN
f  NaN  NaN    5.0
g  NaN  NaN    6.0

In [42]:
r.unstack()

one    a    0.0
       b    1.0
       c    NaN
       d    NaN
       e    NaN
       f    NaN
       g    NaN
two    a    NaN
       b    NaN
       c    2.0
       d    3.0
       e    4.0
       f    NaN
       g    NaN
three  a    NaN
       b    NaN
       c    NaN
       d    NaN
       e    NaN
       f    5.0
       g    6.0
dtype: float64

### dataframe

In [43]:
df1 = pd.DataFrame(np.arange(6).reshape((3,2)), index=list('abc'), columns=['one', 'two'])
df1

one  two
a    0    1
b    2    3
c    4    5

In [44]:
df2 = pd.DataFrame(5 + np.arange(4).reshape((2,2)), index=list('ac'), columns=['three', 'four'])
df2

three  four
a      5     6
c      7     8

### simple concat

In [45]:
pd.concat([df1, df2], axis=1, keys=['lvl1', 'lvl2'], sort=True)

lvl1      lvl2     
   one two three four
a    0   1   5.0  6.0
b    2   3   NaN  NaN
c    4   5   7.0  8.0

### concat with dict

In [46]:
pd.concat({'lvl1': df1, 'lvl2': df2}, axis=1, sort=True)

lvl1      lvl2     
   one two three four
a    0   1   5.0  6.0
b    2   3   NaN  NaN
c    4   5   7.0  8.0

In [47]:
pd.concat({'lvl1': df1, 'lvl2': df2}, axis=0, sort=True)

four  one  three  two
lvl1 a   NaN  0.0    NaN  1.0
     b   NaN  2.0    NaN  3.0
     c   NaN  4.0    NaN  5.0
lvl2 a   6.0  NaN    5.0  NaN
     c   8.0  NaN    7.0  NaN

In [48]:
pd.concat({'lvl1': df1, 'lvl2': df2}, axis=1, sort=True)

lvl1      lvl2     
   one two three four
a    0   1   5.0  6.0
b    2   3   NaN  NaN
c    4   5   7.0  8.0

## Combines

In [49]:
a = pd.Series([np.nan, 2.5, np.nan, 3.5, 4.5, np.nan], index=list('fedcba'), dtype=np.float64)
a

f    NaN
e    2.5
d    NaN
c    3.5
b    4.5
a    NaN
dtype: float64

In [50]:
b = pd.Series(np.arange(len(a), dtype=np.float64), index=list('fedcba'))
b[-1] = np.nan
b

f    0.0
e    1.0
d    2.0
c    3.0
b    4.0
a    NaN
dtype: float64

### where

In [51]:
d = np.where(pd.isnull(a), b, a)
d = pd.Series(d, index=a.index)
d

f    0.0
e    2.5
d    2.0
c    3.5
b    4.5
a    NaN
dtype: float64

### combine_first + series

In [52]:
b.combine_first(a)

f    0.0
e    1.0
d    2.0
c    3.0
b    4.0
a    NaN
dtype: float64

In [53]:
a.combine_first(b)

f    0.0
e    2.5
d    2.0
c    3.5
b    4.5
a    NaN
dtype: float64

### combine_first dataframe

In [54]:
df1 = pd.DataFrame({'а': [1., np.nan, 5., np.nan], 
                    'b': [np.nan, 2., np.nan, 6.], 
                    'с': range(2, 18, 4)}) 
df1

а    b   с
0  1.0  NaN   2
1  NaN  2.0   6
2  5.0  NaN  10
3  NaN  6.0  14

In [55]:
df2 = pd.DataFrame({'а': [5., 4., np.nan, 3., 7.], 
                    'b': [np.nan, 3., 4., 6., 8.]})
df2

а    b
0  5.0  NaN
1  4.0  3.0
2  NaN  4.0
3  3.0  6.0
4  7.0  8.0

In [56]:
df1.combine_first(df2)

b    а     с
0  NaN  1.0   2.0
1  2.0  4.0   6.0
2  4.0  5.0  10.0
3  6.0  3.0  14.0
4  8.0  7.0   NaN